/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AberturaRouteImport } from './routes/abertura'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComponentesRouteImport } from './routes/componentes'
import { Route as CoresRouteImport } from './routes/cores'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as IconesRouteImport } from './routes/icones'
import { Route as MarcaRouteImport } from './routes/marca'
import { Route as SiteRouteImport } from './routes/site'
import { Route as TipografiaRouteImport } from './routes/tipografia'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAssistirRouteImport } from './routes/app.assistir'
import { Route as AppCarteiraRouteImport } from './routes/app.carteira'
import { Route as AppContaRouteImport } from './routes/app.conta'
import { Route as AppEcossistemaRouteImport } from './routes/app.ecossistema'
import { Route as AppEstudioRouteImport } from './routes/app.estudio'
import { Route as AppJukeboxRouteImport } from './routes/app.jukebox'
import { Route as AppModeracaoRouteImport } from './routes/app.moderacao'
import { Route as AppPerfisRouteImport } from './routes/app.perfis'
import { Route as AppSynthRouteImport } from './routes/app.synth'
import { Route as AppVitrineRouteImport } from './routes/app.vitrine'
import { Route as SiteIndexRouteImport } from './routes/site.index'
import { Route as SiteCriadoresRouteImport } from './routes/site.criadores'
import { Route as SiteEcossistemaRouteImport } from './routes/site.ecossistema'
import { Route as SiteInvestidoresRouteImport } from './routes/site.investidores'
import { Route as SiteSegurancaRouteImport } from './routes/site.seguranca'
import { Route as Char91__componentChar93PreviewSplatRouteImport } from './routes/[__component].preview.$'
import { Route as Char91__mockupChar93PreviewSplatRouteImport } from './routes/[__mockup].preview.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AberturaRoute = AberturaRouteImport.update({
  id: '/abertura',
  path: '/abertura',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentesRoute = ComponentesRouteImport.update({
  id: '/componentes',
  path: '/componentes',
  getParentRoute: () => rootRouteImport,
} as any)
const CoresRoute = CoresRouteImport.update({
  id: '/cores',
  path: '/cores',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const IconesRoute = IconesRouteImport.update({
  id: '/icones',
  path: '/icones',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaRoute = MarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const TipografiaRoute = TipografiaRouteImport.update({
  id: '/tipografia',
  path: '/tipografia',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistirRoute = AppAssistirRouteImport.update({
  id: '/assistir',
  path: '/assistir',
  getParentRoute: () => AppRoute,
} as any)
const AppCarteiraRoute = AppCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AppRoute,
} as any)
const AppContaRoute = AppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppRoute,
} as any)
const AppEcossistemaRoute = AppEcossistemaRouteImport.update({
  id: '/ecossistema',
  path: '/ecossistema',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudioRoute = AppEstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => AppRoute,
} as any)
const AppJukeboxRoute = AppJukeboxRouteImport.update({
  id: '/jukebox',
  path: '/jukebox',
  getParentRoute: () => AppRoute,
} as any)
const AppModeracaoRoute = AppModeracaoRouteImport.update({
  id: '/moderacao',
  path: '/moderacao',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfisRoute = AppPerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => AppRoute,
} as any)
const AppSynthRoute = AppSynthRouteImport.update({
  id: '/synth',
  path: '/synth',
  getParentRoute: () => AppRoute,
} as any)
const AppVitrineRoute = AppVitrineRouteImport.update({
  id: '/vitrine',
  path: '/vitrine',
  getParentRoute: () => AppRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCriadoresRoute = SiteCriadoresRouteImport.update({
  id: '/criadores',
  path: '/criadores',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEcossistemaRoute = SiteEcossistemaRouteImport.update({
  id: '/ecossistema',
  path: '/ecossistema',
  getParentRoute: () => SiteRoute,
} as any)
const SiteInvestidoresRoute = SiteInvestidoresRouteImport.update({
  id: '/investidores',
  path: '/investidores',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSegurancaRoute = SiteSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => SiteRoute,
} as any)
const Char91__componentChar93PreviewSplatRoute =
  Char91__componentChar93PreviewSplatRouteImport.update({
    id: '/__component/preview/$',
    path: '/__component/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__mockupChar93PreviewSplatRoute =
  Char91__mockupChar93PreviewSplatRouteImport.update({
    id: '/__mockup/preview/$',
    path: '/__mockup/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abertura': typeof AberturaRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/componentes': typeof ComponentesRoute
  '/cores': typeof CoresRoute
  '/design-system': typeof DesignSystemRoute
  '/icones': typeof IconesRoute
  '/marca': typeof MarcaRoute
  '/site': typeof SiteRouteWithChildren
  '/tipografia': typeof TipografiaRoute
  '/app/assistir': typeof AppAssistirRoute
  '/app/carteira': typeof AppCarteiraRoute
  '/app/conta': typeof AppContaRoute
  '/app/ecossistema': typeof AppEcossistemaRoute
  '/app/estudio': typeof AppEstudioRoute
  '/app/jukebox': typeof AppJukeboxRoute
  '/app/moderacao': typeof AppModeracaoRoute
  '/app/perfis': typeof AppPerfisRoute
  '/app/synth': typeof AppSynthRoute
  '/app/vitrine': typeof AppVitrineRoute
  '/site/criadores': typeof SiteCriadoresRoute
  '/site/ecossistema': typeof SiteEcossistemaRoute
  '/site/investidores': typeof SiteInvestidoresRoute
  '/site/seguranca': typeof SiteSegurancaRoute
  '/app/': typeof AppIndexRoute
  '/site/': typeof SiteIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abertura': typeof AberturaRoute
  '/auth': typeof AuthRoute
  '/componentes': typeof ComponentesRoute
  '/cores': typeof CoresRoute
  '/design-system': typeof DesignSystemRoute
  '/icones': typeof IconesRoute
  '/marca': typeof MarcaRoute
  '/tipografia': typeof TipografiaRoute
  '/app/assistir': typeof AppAssistirRoute
  '/app/carteira': typeof AppCarteiraRoute
  '/app/conta': typeof AppContaRoute
  '/app/ecossistema': typeof AppEcossistemaRoute
  '/app/estudio': typeof AppEstudioRoute
  '/app/jukebox': typeof AppJukeboxRoute
  '/app/moderacao': typeof AppModeracaoRoute
  '/app/perfis': typeof AppPerfisRoute
  '/app/synth': typeof AppSynthRoute
  '/app/vitrine': typeof AppVitrineRoute
  '/site/criadores': typeof SiteCriadoresRoute
  '/site/ecossistema': typeof SiteEcossistemaRoute
  '/site/investidores': typeof SiteInvestidoresRoute
  '/site/seguranca': typeof SiteSegurancaRoute
  '/app': typeof AppIndexRoute
  '/site': typeof SiteIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abertura': typeof AberturaRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/componentes': typeof ComponentesRoute
  '/cores': typeof CoresRoute
  '/design-system': typeof DesignSystemRoute
  '/icones': typeof IconesRoute
  '/marca': typeof MarcaRoute
  '/site': typeof SiteRouteWithChildren
  '/tipografia': typeof TipografiaRoute
  '/app/assistir': typeof AppAssistirRoute
  '/app/carteira': typeof AppCarteiraRoute
  '/app/conta': typeof AppContaRoute
  '/app/ecossistema': typeof AppEcossistemaRoute
  '/app/estudio': typeof AppEstudioRoute
  '/app/jukebox': typeof AppJukeboxRoute
  '/app/moderacao': typeof AppModeracaoRoute
  '/app/perfis': typeof AppPerfisRoute
  '/app/synth': typeof AppSynthRoute
  '/app/vitrine': typeof AppVitrineRoute
  '/site/criadores': typeof SiteCriadoresRoute
  '/site/ecossistema': typeof SiteEcossistemaRoute
  '/site/investidores': typeof SiteInvestidoresRoute
  '/site/seguranca': typeof SiteSegurancaRoute
  '/app/': typeof AppIndexRoute
  '/site/': typeof SiteIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abertura'
    | '/app'
    | '/auth'
    | '/componentes'
    | '/cores'
    | '/design-system'
    | '/icones'
    | '/marca'
    | '/site'
    | '/tipografia'
    | '/app/assistir'
    | '/app/carteira'
    | '/app/conta'
    | '/app/ecossistema'
    | '/app/estudio'
    | '/app/jukebox'
    | '/app/moderacao'
    | '/app/perfis'
    | '/app/synth'
    | '/app/vitrine'
    | '/site/criadores'
    | '/site/ecossistema'
    | '/site/investidores'
    | '/site/seguranca'
    | '/app/'
    | '/site/'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abertura'
    | '/auth'
    | '/componentes'
    | '/cores'
    | '/design-system'
    | '/icones'
    | '/marca'
    | '/tipografia'
    | '/app/assistir'
    | '/app/carteira'
    | '/app/conta'
    | '/app/ecossistema'
    | '/app/estudio'
    | '/app/jukebox'
    | '/app/moderacao'
    | '/app/perfis'
    | '/app/synth'
    | '/app/vitrine'
    | '/site/criadores'
    | '/site/ecossistema'
    | '/site/investidores'
    | '/site/seguranca'
    | '/app'
    | '/site'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
  id:
    | '__root__'
    | '/'
    | '/abertura'
    | '/app'
    | '/auth'
    | '/componentes'
    | '/cores'
    | '/design-system'
    | '/icones'
    | '/marca'
    | '/site'
    | '/tipografia'
    | '/app/assistir'
    | '/app/carteira'
    | '/app/conta'
    | '/app/ecossistema'
    | '/app/estudio'
    | '/app/jukebox'
    | '/app/moderacao'
    | '/app/perfis'
    | '/app/synth'
    | '/app/vitrine'
    | '/site/criadores'
    | '/site/ecossistema'
    | '/site/investidores'
    | '/site/seguranca'
    | '/app/'
    | '/site/'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AberturaRoute: typeof AberturaRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComponentesRoute: typeof ComponentesRoute
  CoresRoute: typeof CoresRoute
  DesignSystemRoute: typeof DesignSystemRoute
  IconesRoute: typeof IconesRoute
  MarcaRoute: typeof MarcaRoute
  SiteRoute: typeof SiteRouteWithChildren
  TipografiaRoute: typeof TipografiaRoute
  Char91__componentChar93PreviewSplatRoute: typeof Char91__componentChar93PreviewSplatRoute
  Char91__mockupChar93PreviewSplatRoute: typeof Char91__mockupChar93PreviewSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abertura': {
      id: '/abertura'
      path: '/abertura'
      fullPath: '/abertura'
      preLoaderRoute: typeof AberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/componentes': {
      id: '/componentes'
      path: '/componentes'
      fullPath: '/componentes'
      preLoaderRoute: typeof ComponentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cores': {
      id: '/cores'
      path: '/cores'
      fullPath: '/cores'
      preLoaderRoute: typeof CoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icones': {
      id: '/icones'
      path: '/icones'
      fullPath: '/icones'
      preLoaderRoute: typeof IconesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca': {
      id: '/marca'
      path: '/marca'
      fullPath: '/marca'
      preLoaderRoute: typeof MarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tipografia': {
      id: '/tipografia'
      path: '/tipografia'
      fullPath: '/tipografia'
      preLoaderRoute: typeof TipografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistir': {
      id: '/app/assistir'
      path: '/assistir'
      fullPath: '/app/assistir'
      preLoaderRoute: typeof AppAssistirRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/carteira': {
      id: '/app/carteira'
      path: '/carteira'
      fullPath: '/app/carteira'
      preLoaderRoute: typeof AppCarteiraRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conta': {
      id: '/app/conta'
      path: '/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AppContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ecossistema': {
      id: '/app/ecossistema'
      path: '/ecossistema'
      fullPath: '/app/ecossistema'
      preLoaderRoute: typeof AppEcossistemaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estudio': {
      id: '/app/estudio'
      path: '/estudio'
      fullPath: '/app/estudio'
      preLoaderRoute: typeof AppEstudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jukebox': {
      id: '/app/jukebox'
      path: '/jukebox'
      fullPath: '/app/jukebox'
      preLoaderRoute: typeof AppJukeboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/moderacao': {
      id: '/app/moderacao'
      path: '/moderacao'
      fullPath: '/app/moderacao'
      preLoaderRoute: typeof AppModeracaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfis': {
      id: '/app/perfis'
      path: '/perfis'
      fullPath: '/app/perfis'
      preLoaderRoute: typeof AppPerfisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/synth': {
      id: '/app/synth'
      path: '/synth'
      fullPath: '/app/synth'
      preLoaderRoute: typeof AppSynthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vitrine': {
      id: '/app/vitrine'
      path: '/vitrine'
      fullPath: '/app/vitrine'
      preLoaderRoute: typeof AppVitrineRouteImport
      parentRoute: typeof AppRoute
    }
    '/site/': {
      id: '/site/'
      path: '/'
      fullPath: '/site/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/criadores': {
      id: '/site/criadores'
      path: '/criadores'
      fullPath: '/site/criadores'
      preLoaderRoute: typeof SiteCriadoresRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/ecossistema': {
      id: '/site/ecossistema'
      path: '/ecossistema'
      fullPath: '/site/ecossistema'
      preLoaderRoute: typeof SiteEcossistemaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/investidores': {
      id: '/site/investidores'
      path: '/investidores'
      fullPath: '/site/investidores'
      preLoaderRoute: typeof SiteInvestidoresRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/seguranca': {
      id: '/site/seguranca'
      path: '/seguranca'
      fullPath: '/site/seguranca'
      preLoaderRoute: typeof SiteSegurancaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/__component/preview/$': {
      id: '/__component/preview/$'
      path: '/__component/preview/$'
      fullPath: '/__component/preview/$'
      preLoaderRoute: typeof Char91__componentChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__mockup/preview/$': {
      id: '/__mockup/preview/$'
      path: '/__mockup/preview/$'
      fullPath: '/__mockup/preview/$'
      preLoaderRoute: typeof Char91__mockupChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAssistirRoute: typeof AppAssistirRoute
  AppCarteiraRoute: typeof AppCarteiraRoute
  AppContaRoute: typeof AppContaRoute
  AppEcossistemaRoute: typeof AppEcossistemaRoute
  AppEstudioRoute: typeof AppEstudioRoute
  AppJukeboxRoute: typeof AppJukeboxRoute
  AppModeracaoRoute: typeof AppModeracaoRoute
  AppPerfisRoute: typeof AppPerfisRoute
  AppSynthRoute: typeof AppSynthRoute
  AppVitrineRoute: typeof AppVitrineRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistirRoute: AppAssistirRoute,
  AppCarteiraRoute: AppCarteiraRoute,
  AppContaRoute: AppContaRoute,
  AppEcossistemaRoute: AppEcossistemaRoute,
  AppEstudioRoute: AppEstudioRoute,
  AppJukeboxRoute: AppJukeboxRoute,
  AppModeracaoRoute: AppModeracaoRoute,
  AppPerfisRoute: AppPerfisRoute,
  AppSynthRoute: AppSynthRoute,
  AppVitrineRoute: AppVitrineRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SiteRouteChildren {
  SiteCriadoresRoute: typeof SiteCriadoresRoute
  SiteEcossistemaRoute: typeof SiteEcossistemaRoute
  SiteInvestidoresRoute: typeof SiteInvestidoresRoute
  SiteSegurancaRoute: typeof SiteSegurancaRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteCriadoresRoute: SiteCriadoresRoute,
  SiteEcossistemaRoute: SiteEcossistemaRoute,
  SiteInvestidoresRoute: SiteInvestidoresRoute,
  SiteSegurancaRoute: SiteSegurancaRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AberturaRoute: AberturaRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ComponentesRoute: ComponentesRoute,
  CoresRoute: CoresRoute,
  DesignSystemRoute: DesignSystemRoute,
  IconesRoute: IconesRoute,
  MarcaRoute: MarcaRoute,
  SiteRoute: SiteRouteWithChildren,
  TipografiaRoute: TipografiaRoute,
  Char91__componentChar93PreviewSplatRoute:
    Char91__componentChar93PreviewSplatRoute,
  Char91__mockupChar93PreviewSplatRoute: Char91__mockupChar93PreviewSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
